

=head1 Simulation

Model is very important. It must be as detailed as possible but not more becuase it will make impossible to illustrate how real system work.

In this model I will borrow a litle from HLA IEEE 1516 but not all. I don't plan distributed system so there is no need to create separate RTI and all the world descriptions. Anyway it is so easy to inject objects into running perl6 application that even ontology is waste of time. No federates -- objects can have own logic.

The simulation will be made of objects that will affect each other via interactions just like High Level Architecture does.

=head2 Area

Position of object is not important for simulation but area that object come interaction with. Area is the maximum range that any objects may recieve or want to interact HLA simulation designers already knew that and introduced that as part of standard.

=head3 Rectangle

It was easy to use rectangle for simulation. It can be defined by only four numbers and it is trivial to define its overlaping. 

Planes overlap each other if at least one of vertex is above lower vertex of second plane and below upper vertex corners. 

     for $rect1.toVertex -> $vertex {
       $rect2.x[0] <= $vertex.x >= $rect.x[1];
       $rect2.y[0] <= $vertex.y >= $rect.y[1];
     }

=head2 Object 

Bananabanana

=head2 Interaction

Interaction has area of... bnana bnana
 
