

=head1 Simulation

Model is very important. It must be as detailed as possible but not more...

In this model I will borrow a litle from HLA IEEE 1516 but not RTI. 

The simulation will be made of objects that will affect each other via interactions just like High Level Architecture does.

Areas that were optional in HLA here will be base feature.

=head2 Area

Position of object is not important for simulation but area that object come interaction with. Area is the maximum range that any objects may recieve or want to interact HLA simulation designers already knew that and introduced that as part of standard.

=head3 Rectangle

It was easy to use rectangle for simulation. It can be defined by only four numbers and it is trivial to define its overlaping. 

Planes overlap each other if at least one of vertex is above lower vertex of second plane and below upper vertex corners. 

     for $rect1.toVertex -> $vertex {
       $rect2.x[0] <= $vertex.x >= $rect.x[1];
       $rect2.y[0] <= $vertex.y >= $rect.y[1];
     }

=head3 Target

Target is special area of simulation that will match single object. I hope storing references will not give worse performance than using ObjAt. Anyway it will be easy to override overlap method... especilly if C<eqv> will start working on complex objects without any effort.

=head3 Wildcard

Wildcard is B<Area> that allows to interact with all objects.  

=head2 Object 

Unlike to HLA object it can be target of interactions. To achieve this every object must have list B<Area> objects. This list and its contents may change in any moment. So B<Simulation> 

=head2 Interaction

Interaction has area of... bnana bnana
 
